include:
  - local: /.gitlab/tools.yml

stages:
  - status-pre
  - build
  - status-post

build-python:
  extends:
    - .build-python
  stage: build
  script:
    - pip install coverage
    - make test
  artifacts:
    expire_in: 7 days
    paths:
      - .coverage
      - coverage.xml
      - htmlcov/

# commit status
climate-pending:
  stage: status-pre
  extends:
    - .build-climate

  script:
    - cc-test-reporter before-build

climate-success:
  stage: status-post
  extends:
    - .build-climate

  dependencies:
    - build-python
  script:
    - make upload-climate

codecov-success:
  stage: status-post
  extends:
    - .build-codecov

  when: on_success
  dependencies:
    - build-python
  script:
    - make upload-codecov

github-pending:
  stage: status-pre
  extends:
    - .build-curl
  script:
    - ./scripts/github-status.sh pending

github-failure:
  stage: status-post
  extends:
    - .build-curl
  when: on_failure
  script:
    - ./scripts/github-status.sh failure

github-success:
  stage: status-post
  extends:
    - .build-curl
  when: on_success
  script:
    - ./scripts/github-status.sh success
